version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18  # or whatever your code needs
  pre_build:
    commands:
      - echo "Getting ready to check the code"
  build:
    commands:
      - echo "Checking the code now"
      - npm install  # if you have a Node.js project
      - npm test     # if you have tests
  post_build:
    commands:
      - echo "Code check complete!"
